version: '3.1'

services:

  postgres-container:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=ftn
      - POSTGRES_USER=ftn
    volumes:
      - ftn-data:/var/lib/postgresql/data


  ftn-container:
    build: ./FTNBackend 
    ports:
      - "8081:8081"
    volumes:
      - ./FTNBackend:/app
    depends_on:
      - postgres-container


  pmf-container:
    build: ./PMFBackend 
    ports:
      - "8082:8082"
    volumes:
      - ./PMFBackend:/app
    depends_on:
      - pmf-postgres


  pmf-postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=ftn
      - POSTGRES_USER=ftn
    volumes:
      - pmf-data:/var/lib/postgresql/data


  pravni-container:
    build: ./PRAVNIBackend 
    ports:
      - "8083:8083"
    volumes:
      - ./PRAVNIBackend:/app
    depends_on:
      - pravni-postgres


  pravni-postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=ftn
      - POSTGRES_USER=ftn
    volumes:
      - pravni-data:/var/lib/postgresql/data


  uns-postgres:
    image: postgres   
    container_name: uns-postgres
    volumes:
      - uns-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart: unless-stopped

  uns1:
    build: ./UNS
    container_name: uns1
    ports:
      - 9001:8080
    depends_on:
      - uns-postgres
    volumes:
      - ./UNS/src:/var/tmp
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://uns-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  
  uns2:
    build: ./UNS
    container_name: uns2
    ports:
      - 9002:8080
    depends_on:
      - uns-postgres
    volumes:
      - ./UNS/src:/var/tmp
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://uns-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - uns1
      - uns2
    ports:
      - 80:80
      
volumes:
  ftn-data:
  pravni-data:
  pmf-data:
  uns-data: