version: '3.1'

services:

  postgres-container:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=ftn
      - POSTGRES_USER=ftn
    volumes:
      - ftn-data:/var/lib/postgresql/data
    networks:
      - cloud-network

  ftn-container:
    build: ./FTNBackend 
    ports:
      - "8081:8081"
    volumes:
      - ./FTNBackend:/app
    depends_on:
      - postgres-container
    networks:
      - cloud-network

  pmf-container:
    build: ./PMFBackend 
    ports:
      - "8082:8082"
    volumes:
      - ./PMFBackend:/app
    depends_on:
      - pmf-postgres
    networks:
      - cloud-network

  pmf-postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=ftn
      - POSTGRES_USER=ftn
    volumes:
      - pmf-data:/var/lib/postgresql/data
    networks:
      - cloud-network

  pravni-container:
    build: ./PRAVNIBackend 
    ports:
      - "8083:8083"
    volumes:
      - ./PRAVNIBackend:/app
    depends_on:
      - pravni-postgres
    networks:
      - cloud-network

  pravni-postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=ftn
      - POSTGRES_USER=ftn
    volumes:
      - pravni-data:/var/lib/postgresql/data
    networks:
      - cloud-network

networks:
  cloud-network:
    external: true

volumes:
  ftn-data:
  pravni-data:
  pmf-data: