version: '3.1'

services:

  postgres-container:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=ftn
      - POSTGRES_USER=ftn
    networks:
      - cloud-network

  ftn-container:
    build: ./FTNBackend 
    ports:
      - "8081:8081"
    volumes:
      - ./FTNBackend:/app
    depends_on:
      - postgres-container
    networks:
      - cloud-network

  pmf-container:
    build: ./PMFBackend 
    ports:
      - "8082:8082"
    volumes:
      - ./PMFBackend:/app
    depends_on:
      - postgres-container
    networks:
      - cloud-network

  pmf-postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=ftn
      - POSTGRES_USER=ftn
    networks:
      - cloud-network

networks:
  cloud-network:
    external: true
