# Generated by Django 4.1.2 on 2023-01-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_professor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
