# Generated by Django 4.1.2 on 2023-01-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_professor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
