version: "3"
services:
  postgres:
    image: 'postgres:13.1-alpine'    
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_USER=user
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=postgres
    restart: unless-stopped
    networks:
      - cloud-network

  uns:
    image: unsimg:latest
    container_name: uns
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
          - /src:/var/tmp
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - cloud-network

networks:
  cloud-network:
    external: true

volumes:
  postgres-data:

