name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./UNS
          push: true
          tags: poparicsara/uns:1.0
          
      - name: Build and push
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: ./FTNBackend
          push: true
          tags: poparicsara/ftn:1.0
      
      - name: Build and push
        id: docker_build3
        uses: docker/build-push-action@v2
        with:
          context: ./PMFBackend
          push: true
          tags: poparicsara/pmf:1.0
      
      - name: Build and push
        id: docker_build4
        uses: docker/build-push-action@v2
        with:
          context: ./PRAVNIBackend
          push: true
          tags: poparicsara/pravni:1.0
